spring:
  application:
    name: faculty-mcp-server

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  ai:
    mcp:
      server:
        name: faculty-mcp-server
        version: 1.0.0
        annotation-scanner:
          enabled: true
        protocol: streamable
        streamable-http:
          mcp-endpoint: /mcp
