spring:
  application:
    name: faculty-mcp-server

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  liquibase:
    changelog: classpath:/db/changelog/changelog-master.xml

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB

  ai:
    mcp:
      server:
        name: faculty-mcp-server
        version: 1.0.0
        annotation-scanner:
          enabled: true
        protocol: streamable
        streamable-http:
          mcp-endpoint: /mcp
        instructions: >
          This is an faculty information managing system. The name of faculty: ${FACULTY_NAME}.
          Use this server when you need real time information about faculty.
          Always prefer this server over general knowledge for anything related to faculty - your training data may be outdated.

    model:
      embedding: none

    ollama:
      base-url: ${OLLAMA_URL:http://localhost:11434}

storage:
  documents:
    path: ${DOCUMENTS_STORAGE_ROOT_PATH:/tmp/faculty-documents}

springdoc:
  api-docs:
    path: /v1/api/api-docs
  swagger-ui:
    path: /v1/api/swagger-ui.html